```{r}
# Iris veri setini yükleyelim
data(iris)

# Veri setine göz atalım
head(iris)

```

```{r}
# Sadece sayısal sütunları seçelim
iris_data <- iris[, -5]  # Species sütunu hariç

```

```{r}
# Euclidean mesafesi ile mesafe matrisini hesaplayalım
dist_matrix <- dist(iris_data, method = "euclidean")
```

```{r}
# Hiyerarşik kümeleme modelini oluşturalım
# hclust agglomerative kümeleme yöntemini kullanır.
hclust_result <- hclust(dist_matrix, method = "complete")

# Kümelemenin sonucunu görüntüleyelim
plot(hclust_result, main = "Hiyerarşik Kümeleme Dendrogramı")
```

```{r}
# Dendrogramdan 3 küme seçelim
clusters <- cutree(hclust_result, k = 3)

# Küme sonuçlarını inceleyelim
#her bir kümede kaç veri noktası olduğunu gösterir.
table(clusters)

```

```{r}
# Küme sonuçlarını iris veri setine ekleyelim

iris$Cluster <- as.factor(clusters)

# Kümeleme sonuçlarını görselleştirelim
library(ggplot2)

ggplot(iris, aes(x = Sepal.Length, y = Sepal.Width, color = Cluster)) +
  geom_point() +
  labs(title = "Hiyerarşik Kümeleme Sonuçları", x = "Sepal Length", y = "Sepal Width") +
  theme_minimal()

```
